

exec-once = hyprpm reload


plugin {

    csgo-vulkan-fix {
        res_w = 1920
        res_h = 1200

        # NOT a regex! This is a string and has to exactly match initial_class
        class = cs2 
    }

	overview {


	}
}

#bind = Super, Tab, hyprexpo:expo, toggle
