#! /usr/bin/env bash


API_URL="http://wttr.in/{}?format=j2"
CITY="$WEATHER_CITY"
if [ -z "$CITY" ]; then
    CITY="$1"
fi

if [ -z "$TIMEOUT" ]; then
    TIMEOUT=20
fi



get_city(){
    if [ -z "$CITY" ]; then
        CITY=$(curl -s "ipinfo.io/json" | jq -r '.city')
    fi
}

get_weather(){
    url=$(echo $API_URL | sed "s/{}/$CITY/")
    WEATHER=$(curl -s --max-time $TIMEOUT "$url" | jq -r '.current_condition[0]')
    echo "$WEATHER"
}

get_city
WEATHER=$(get_weather)

text=$(echo "$WEATHER" | jq -r '.weatherDesc[0].value')

if [ -z "$WEATHER" ]; then
    echo "Weather unavailable"
else
    echo "{\"text\": \"$text\"}"
fi


