cursor #e1e4da
cursor_text_color #c3c8bb

foreground            #e1e4da
background            #11140f
selection_foreground  #273421
selection_background  #bccbb0
url_color             #a8d292

color0   #11140f
color1   #f1876c
color2   #6ed269
color3   #ffed72
color4   #97c77e
color5   #3d612a
color6   #a8d292
color7   #d3dccf
color8   #81887e
color9   #ffb29f
color10  #a8fba3
color11  #fff3a5
color12  #bfe7ab
color13  #dbffc8
color14  #e8ffdc
color15  #fafff8
