#! /usr/bin/env bash

API_URL="http://wttr.in/{}?format=2"
CITY="$WEATHER_CITY"

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/weather"
# Cache is of format:
# <timestamp> <NL>
# <weather string>

if [ -z "$CACHE_TIMEOUT" ]; then
    CACHE_TIMEOUT=600  # Default cache timeout of 10 mins
fi

if [ -f "$CACHE" ]; then
    read -r last_update < "$CACHE"
    current_time=$(date +%s)
    if (( current_time - last_update < CACHE_TIMEOUT )); then
        cat "$CACHE" | tail -n +2
        exit 0
    fi
fi



if [ -z "$CITY" ]; then
    CITY="$1"
fi

if [ -z "$TIMEOUT" ]; then
    TIMEOUT=10
fi

get_city(){
    if [ -z "$CITY" ]; then
        CITY=$(curl -s "ipinfo.io/json" | jq -r '.city')
    fi
}

get_weather(){
    url=$(echo $API_URL | sed "s/{}/$CITY/")
    WEATHER=$(curl -s --max-time $TIMEOUT "$url")
    echo "$WEATHER"
}

get_city
WEATHER=$(get_weather)

if [ -z "$WEATHER" ]; then
    echo "Weather unavailable"
    exit 1
else
    echo "$CITY: $WEATHER"
fi


# Cache the result
echo "$(date +%s)" > "$CACHE"
echo "$CITY: $WEATHER" >> "$CACHE"
exit 0